# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  # Build pipeline details
  tags: '$(Build.BuildNumber)'
  vmImageName: 'ubuntu-latest'
  frontEndRepoName: 'tapup/frontend-service'
  frontendServiceDirPath: '$(Build.SourcesDirectory)'
  containerRegistryDevDocker: 'tapupgloballowerdock'

#==================== Build TapUp front end application for Development envirnomnet =================
stages:
  - stage: Build_Dev_Environment
    displayName: Build and Push Tapup front end application to ACR
    
    jobs: 
    # ========================== Build Application =====================
    - job: Build_application
      displayName: Building the TapUp application. 
      pool:
        vmImage: $(vmImageName)
      steps:
      # Build the docker image for the microservice.
        - task: Docker@2
          displayName: Build and push
          inputs:
            command: 'buildAndPush'
            containerRegistry: $(containerRegistryDevDocker)
            repository: $(frontEndRepoName)
            Dockerfile: '$(frontendServiceDirPath)/Dockerfile'
            buildContext: '$(frontendServiceDirPath)/'
            tags: |
              $(tags)
              latest      

# =============================== End of dev build stage =======================
