version: '3.5'

services: 
  app:
    container_name: tapup-frontend
    build: 
        context: .
        dockerfile: Dockerfile
    image: tapup-frontend
    volumes: 
      - .:/app
      - '/app/node_modules'
    ports: 
      - '3000:3000'
    command: yarn start

